version: '1'

services:
	postgres:
		image: postgres:9.6
		container_name: postgres
		environment:
			POSTGRES_USER: savings
			POSTGRES_PASSWORD: J5brHrAXFLQSif0K
			POSTGRES_DB: savings

	savings:
		build: .
		image: chamaconekt/savings
		links:
		- postgres
		container_name: savings
		depends_on:
			- postgres
		environment:

	nginx:
		image: nginx:1.11.11-alpine
		links:
			- savings
		container_name: nginx
		command: nginx -g 'daemon off;' -c /etc/savings-nginx/nginx.conf
		depends_on:
			- savings
		ports:
			- 80:80
		volumes_from:
			- savings

volumes:
	savings-static-files:
		driver:local